### ISSUE TITLE
Hooks are unnecessary?

### ISSUE THREAD

**Issue by adamchainz** [Opus10/django-pgconnection#7]
The hooks installed by this library with `pre_execute_hook` seem to be basically a copy of Django’s [database instrumentation](https://docs.djangoproject.com/en/stable/topics/db/instrumentation/), a feature added in Django 2.0.

I cannot see any strong differences, so perhaps downstream usage could be adapted to use Django’s feature instead of requiring a cursor patch?

I covered creating always-installed database instrumentation with the current API here: https://adamj.eu/tech/2020/07/23/how-to-make-always-installed-django-database-instrumentation/ . There may be reasonable demand to add an official API to do this.

**Comment by wesleykendall** [comment]
@adamchainz thanks so much for letting me know about this. This library has been used by me for a while for various projects before Django 2, and I'm so glad they have this available now. Way better than hacking the internals like this app.

I had quite a bit more in mind for this app, and it's effectively just a way to route connections now haha. But at least I can remove the pgtrigger dependency on it

I like your article and think it would be nice too. If it's something you'd be interested in adding here or collaborating on elsewhere, feel free to email me - wesleykendall@protonmail.com

I will update the internals of this and mark this as resolved when I do

**Comment by wesleykendall** [comment]
All dependencies on pgconnection (pgclone, pgtrigger, pghistory) have been replaced with Django hooks. Thanks again for the suggestion!

**Comment by adamchainz** [comment]
Good work!
